service: serverlessSetup

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1

# functions
functions:
  hello:
    handler: src/functions/hello.handler
    events: # The events that trigger this function
      - http:
          path: serverlessSetup/hello
          method: get
  createUser:
    handler: src/functions/createUser.handler
    events:
      - http:
          path: serverlessSetup/create
          method: post
  question:
    handler: src/functions/question.handler
    dependsOn: SNSHelloEvent
    events:
      - sns:
          arn: !Ref SNSHelloEvent
          topicName: hello-event

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

# Resources your functions use
resources:
  Resources:
    # SNS Topics
    SNSHelloEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Hello Event Topic
        TopicName: hello-event
