service: serverlessSetup

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1

# functions
functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: serverlessSetup/hello
          method: get
  createUser:
    handler: src/functions/createUser.handler
    events:
      - http:
          path: serverlessSetup/create
          method: post

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
# Resources your functions use

