service: serverlessSetup

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1

# functions
functions:
  getProduct:
    handler: src/functions/getProducts.handler
    events:
      - http:
          path: serverlessSetup/getProducts
          method: get
  createProduct:
    handler: src/functions/createProduct.handler
    events:
      - http:
          path: serverlessSetup/createProduct
          method: post

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
# Resources your functions use

