service: serverlessSetup

resources:
  extensions:
    S3BucketUploadpng4567:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - POST
                - PUT
                - GET
                - HEAD
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  timeout: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::upload-png-4567/*
# functions
functions:
  authorize:
    handler: src/functions/users/authorize.handler
  getProducts:
    handler: src/functions/products/getProducts.handler
    events:
      - http:
          path: serverless/getProducts
          method: get

  getProduct:
    handler: src/functions/products/getProduct.handler
    events:
      - http:
          path: serverless/getProduct
          method: get

  createProduct:
    handler: src/functions/products/createProduct.handler
    events:
      - http:
          path: serverless/createProduct
          method: post

  updateProduct:
    handler: src/functions/products/updateProduct.handler
    events:
      - http:
          path: serverless/updateProduct
          method: put

  deleteProduct:
    handler: src/functions/products/deleteProduct.handler
    events:
      - http:
          path: serverless/deleteProduct
          method: delete

  addCategory:
    handler: src/functions/categories/addCategory.handler
    events:
      - http:
          path: serverless/addCategory
          method: post
  login:
    handler: src/functions/users/login.handler
    events:
      - http:
          path: serverless/login
          method: get
  getUser:
    handler: src/functions/users/getUser.handler
    events:
      - http:
          path: serverless/user/{email}
          method: get
  s3Test:
    handler: src/functions/s3/s3Function.handler
    events:
      - s3:
          bucket: upload-png-4567
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
  simulateS3Trigger:
    handler: src/functions/s3/simulateS3Trigger.handler
    events:
      - http:
          path: serverless/triggerS3
          method: post
# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-s3-local
