service: serverlessSetup

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1

# functions
functions:
  getProducts:
    handler: src/functions/getProducts.handler
    events:
      - http:
          path: serverless/getProducts
          method: get
  getProduct:
    handler: src/functions/getProduct.handler
    events:
      - http:
          path: serverless/getProduct
          method: get
  createProduct:
    handler: src/functions/createProduct.handler
    events:
      - http:
          path: serverless/createProduct
          method: post
  updateProduct:
    handler: src/functions/updateProduct.handler
    events:
      - http:
          path: serverless/updateProduct
          method: put
  deleteProduct:
    handler: src/functions/deleteProduct.handler
    events:
      - http:
          path: serverless/deleteProduct
          method: delete
  s3Test:
    handler: src/functions/testS3.handler
    events:
      - s3:
          bucket: upload.csv.local4567
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-s3-local
